### ISSUE TITLE
I can't set style

### ISSUE THREAD

**Issue by simbawu610** [svenanders/react-iframe#12]
when I set `style={{color: '#ddd'}}`  it can't work
`<Iframe url={day.desc_url} width="100%" height="600px" style={{color: '#ddd'}}
                  position="relative" allowFullScreen/>`

**Comment by svenanders** [comment]
It's *styles* and not *style*, but I'll make a release shortly that adds an alias for *style*as well

**Comment by simbawu610** [comment]
Oh,I made such a low mistake. Thanks!
