### ISSUE TITLE
How to listen to URL changes inside the iframe and prevent URL from redirecting!

### ISSUE THREAD

**Issue by marwajomaa** [svenanders/react-iframe#138]

**Comment by maxwhoppa** [comment]
what was the soln here?

**Comment by maxwhoppa** [comment]
I have a use case where I want to check if it redirects to a url on our own webpage (so it does not break the security rules) but I don't see a way to pass a ref in here

**Comment by marwajomaa** [comment]
@maxwhoppa  I didn't use this one and  I use HTML iframe as I didn't find anything special to use it. besides that it's hard to listen to URL changes due to browser security especially when iframe content is external, so I couldn't listen to URL changes. prevented the URL redirect with some state to hide the iframe once the redirect happens. hope that clear
