### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by ironLink21** [svenanders/react-iframe#16]
It looks like when trying to use this component in IE11 it throws errors for "SCRIPT438: Object doesn't support property or method 'assign' "  which tracking down the issue means that it doesn't like Object.assign() 

I found a workaround if you want to try it (if you really want to support IE11) to use the object-assign package here: https://github.com/sindresorhus/object-assign instead of the native Object.assign()

**Comment by dylanpinn** [comment]
I had a similar problem and fixed it by adding polyfills to add the missing methods.

**Comment by ironLink21** [comment]
It was interesting because I had polyfills instead but it must have been caching because it's working now.
