### ISSUE TITLE
Allow for setting title or aria-label for accessibility reasons

### ISSUE THREAD

**Issue by CL0SeY** [svenanders/react-iframe#41]
We have a requirement which has been exposed by the "axe" developer tool which shows that we have an issue with the iframe not including a title or label:

**Issue description**
Ensures <iframe> and <frame> elements contain a non-empty title attribute

**Impact: serious**
Element location
iframe
Element source
`<iframe frameborder="0" src="<snip>" target="_parent" allowfullscreen="" height="100%" name="" width="100%" style="position: absolute; display: block; height: 100%; width: 100%;"></iframe>`
To solve this violation, you need to:
Fix at least one (1) of these issues:

- aria-label attribute does not exist or is empty
- aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
- Element has no title attribute or the title attribute is empty
- Element's default semantics were not overridden with role="presentation"
- Element's default semantics were not overridden with role="none"

Would be good if, in the simplest case, an optional "title" attribute could be passed through into the HTML.

**Comment by svenanders** [comment]
Added to latest version (1.7.2). Please let me know if it's okay or if I need to add more aria-props!
