### ISSUE TITLE
What's going on with the update/release commits?

### ISSUE THREAD

**Issue by polarathene** [svenanders/react-iframe#48]
Looking over the commit history to see what had changed since earlier this year. The `CHANGELOG.md`(or releases page) isn't too useful since commit messages adding changes often either don't use the keywords it expects at all or uses them incorrectly(part of a chore for release). 

You have a pattern of release commits sometimes 2-3 times in a row. Usually only the first may contain actual changes or be for a prior commit. The others [just seem to be version bumps](https://github.com/svenanders/react-iframe/commit/f64e8e565ee6569576eafef706ec91fe71f5d922) for no reason? Is this a bug with some release automation?

**Comment by svenanders** [comment]
I know, the update script was completely wacky... :( Have changed it since 1.7.8 to avoid the multiple commits, and I should also remember to actually use conventional commits structure... Sorry about that, and thanks for pointing it out.
