### ISSUE TITLE
How to set styles to component?

### ISSUE THREAD

**Issue by Sunil6591** [svenanders/react-iframe#5]
I am trying to set 

```
<IFrame style={{position: 'fixed', width: '100%', height: '100%', left: 0}} url={...}  />
```

But its not applying

**Comment by smhatre59** [comment]
The code used internally is : 
React.createElement("iframe", { ref: "iframe",
            frameBorder: "0",
            src: this.props.url,
            style: { position: this.props.position, height: this.props.height, width: this.props.width },
            height: this.props.height, width: this.props.width });

So you can set width and height using props as follows:
<Iframe url={embedUrl} height="500" width="600"/>

**Comment by svenanders** [comment]
Yep, that works, but I guess if you want more styles then that is not enough. Added a styles prop now!
