### ISSUE TITLE
Support the lazy-loading `loading` attribute

### ISSUE THREAD

**Issue by polarathene** [svenanders/react-iframe#50]
https://addyosmani.com/blog/lazy-loading/

The `loading` attribute can take the values `auto,eager,lazy`, browsers that support the attribute may implicitly default to `auto` to determine if they should use `eager` or `lazy` based on distance from viewport. The attribute communicates to the browser how important the image/iframe resource is to prioritize loading, potentially delaying it while it's not within a viewing distance from the current viewport.

**Comment by svenanders** [comment]
Ok, added! :)
