### ISSUE TITLE
scrolling and allowTransparency

### ISSUE THREAD

**Issue by monolithed** [svenanders/react-iframe#6]
Hi, what about these properties?

**Comment by svenanders** [comment]
I'm not sure about these props. Neither is supported in HTML5. How about passing these as a style prop instead. For instance:

    <Iframe url="http://www.example.com"
                position="absolute"
                width="50%"
                height="50%"
                styles={{backgroundColor: "transparent", overflow: "hidden"}}/> 

These two styles are equivalent to "allowTransparency" and scrolling: no. 

https://www.w3.org/TR/html5-diff/
